[project]
name = "uv-sample-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rumen", email = "rumenmitov@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
    "rich>=15.0.0",
]

[project.scripts]
uv-sample-project = "uv_sample_project:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
